### ISSUE TITLE
Add better warning

### ISSUE THREAD

**Issue by gibbok** [actyx-contrib/actyx-project-cli#14]
Create a new app for a project, now run it in the browser but without having ActyxOS, nothing appears.
If you open console we get error:
```
webSocketSubject.js:69 WebSocket connection to 'ws://localhost:4243/store_api' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Maybe we can add a more friendly error message in condole dev tools, like "Please make sure ActyxOS is running" or similar

**Comment by Alexander89** [comment]
This is done in the Pond already.
